# Generated by Django 3.2.3 on 2021-05-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
