# Generated by Django 3.2.3 on 2021-05-22 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('770b5471-5ed3-4dc4-b269-3e21b8e4f5e5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
