# Generated by Django 3.2.3 on 2021-05-22 16:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a426bdc-bb1c-11eb-8d4d-5d8e31977021'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
