# Generated by Django 3.2.3 on 2021-06-15 11:25

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210614_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='defaultProfile.png', upload_to=account.models.get_upload_directory),
        ),
    ]
