# Generated by Django 3.2.3 on 2021-06-15 12:31

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/defaultProfile.png', null=True, upload_to=account.models.get_upload_directory),
        ),
    ]
