# Generated by Django 3.2.3 on 2021-06-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ku_quora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ku_quora.post')),
            ],
        ),
    ]
