# Generated by Django 3.2.3 on 2021-06-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_quora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='<function uuid4 at 0x7efd671fe670>', max_length=200, primary_key=True, serialize=False),
        ),
    ]
