# Generated by Django 3.2.3 on 2021-06-15 11:12

from django.db import migrations, models
import ku_quora.models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_quora', '0002_postimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(upload_to=ku_quora.models.get_file_path),
        ),
    ]
