# Generated by Django 3.2.2 on 2021-06-23 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ku_quora', '0002_dislike_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ansID', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ku_quora.answer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ku_quora.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
