# Generated by Django 3.2.6 on 2021-08-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_quora', '0002_alter_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.TextField(max_length=1000),
        ),
    ]
