# Generated by Django 3.2.2 on 2021-06-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ku_quora', '0003_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='parent',
        ),
    ]
