# Generated by Django 3.2.4 on 2021-07-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ku_quora', '0003_auto_20210625_1308'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='user_from',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='user_to',
        ),
        migrations.AddField(
            model_name='notification',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ku_quora.answer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'like'), (2, 'follow'), (3, 'post'), (4, 'answer')], default=0),
        ),
    ]
