# Generated by Django 3.2.3 on 2021-05-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'like'), (2, 'dislike'), (3, 'follow')], default=0),
        ),
    ]
