# Generated by Django 3.2.4 on 2021-07-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210705_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'upVote'), (2, 'follow'), (3, 'post'), (4, 'answer')], default=0),
        ),
    ]
